name: Python testing
on:
  push: null
jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml
        cache: pip
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: '${{ runner.os }}-pip-

          ${{ runner.os }}-

          '
    - name: Install dependencies
      run: "python -m pip install --upgrade pip\n# Prefer requirements-dev.txt\nif [ -f requirements-dev.txt\
        \ ]; then\n  scripts/install_requirements requirements-dev.txt \"${{ secrets.ADMIN_GITHUB_TOKEN\
        \ }}\"\nelif [ -f requirements-test.txt ]; then\n  scripts/install_requirements requirements-test.txt\
        \ \"${{ secrets.ADMIN_GITHUB_TOKEN }}\"\nelif [ -f requirements.txt ]; then\n  scripts/install_requirements\
        \ requirements.txt \"${{ secrets.ADMIN_GITHUB_TOKEN }}\"\nfi\n\nif [ -d custom_components ]; then\n\
        \  echo '\"\"\"Stub.\"\"\"' >custom_components/__init__.py\nfi\n"
    - name: Lint
      run: python3 -m ruff check .
    - name: Format
      run: python3 -m ruff format . --check
    - name: Install dependencies
      run: "python -m pip install --upgrade pip\n# Prefer requirements-test.txt\nif [ -f requirements-test.txt\
        \ ]; then\n  scripts/install_requirements requirements-test.txt \"${{ secrets.ADMIN_GITHUB_TOKEN\
        \ }}\"\nelif [ -f requirements-dev.txt ]; then\n  scripts/install_requirements requirements-dev.txt\
        \ \"${{ secrets.ADMIN_GITHUB_TOKEN }}\"\nelif [ -f requirements.txt ]; then\n  scripts/install_requirements\
        \ requirements.txt \"${{ secrets.ADMIN_GITHUB_TOKEN }}\"\nfi\npip install pytest-xdist\n\nif [\
        \ -d custom_components ]; then\n  echo '\"\"\"Stub.\"\"\"' >custom_components/__init__.py\nfi\n"
    - name: Install Coveralls
      run: 'pip install pytest-xdist coveralls

        '
    - name: Run tests with pytest & Calculate coverage
      run: 'pytest --basetemp=$RUNNER_TEMP --durations=10 -n auto --dist=loadfile -qq -o console_output_style=count
        -p no:sugar --cov --cov-report=

        ./scripts/check_dirty

        '
    - name: Send coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
